---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: rotations.rotation.security.io
spec:
  group: rotation.security.io
  names:
    kind: Rotation
    listKind: RotationList
    plural: rotations
    singular: rotation
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Rotation is the Schema for the rotations API
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            description: spec defines the desired state of Rotation
            properties:
              includeSymbols:
                default: true
                description: 'OPTIONAL: Include symbols in the generated password.'
                type: boolean
              passwordLength:
                default: 16
                description: 'OPTIONAL: Desired length of the generated password (default
                  16).'
                type: integer
              rotationInterval:
                description: 'REQUIRED: How often the password should be rotated (e.g.,
                  "24h", "7d").'
                type: string
              vaultPath:
                description: 'REQUIRED: Name of the Vault secret path where the new
                  password will be stored (e.g., "secret/data/my-app/db-creds").'
                type: string
            required:
            - rotationInterval
            - vaultPath
            type: object
          status:
            description: status defines the observed state of Rotation
            properties:
              lastRotatedTime:
                description: |-
                  INSERT ADDITIONAL STATUS FIELDS - define observed state of cluster
                  La última vez que se rotó el secreto con éxito.
                format: date-time
                type: string
              status:
                description: El estado actual (e.g., "Ready", "Error", "Rotating").
                type: string
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
